#!/bin/bash

#SCREEN="DisplayPort-0"
SCREEN="HDMI-A-0"

SCREEN_INFO=$(xrandr | grep "^$SCREEN")

# Extract resolution and offsets correctly
if echo "$SCREEN_INFO" | grep -q "primary"; then
  RESOLUTION=$(echo "$SCREEN_INFO" | awk '{print $4}' | cut -d+ -f1)
  OFFSET_X=$(echo "$SCREEN_INFO" | awk '{print $4}' | cut -d+ -f2)
  OFFSET_Y=$(echo "$SCREEN_INFO" | awk '{print $4}' | cut -d+ -f3)
else
  RESOLUTION=$(echo "$SCREEN_INFO" | awk '{print $3}' | cut -d+ -f1)
  OFFSET_X=$(echo "$SCREEN_INFO" | awk '{print $3}' | cut -d+ -f2)
  OFFSET_Y=$(echo "$SCREEN_INFO" | awk '{print $3}' | cut -d+ -f3)
fi

#-f alsa -i default \
#-f pulse -i alsa_output.pci-0000_00_1f.3.analog-stereo.monitor \

ffmpeg -f x11grab -framerate 30 \
  -video_size "$RESOLUTION" -i :0.0+$OFFSET_X,$OFFSET_Y \
  -f pulse -i alsa_output.pci-0000_00_1f.3.analog-stereo.monitor \
  -f pulse -i alsa_input.usb-BLUE_MICROPHONE_Blue_Snowball_201306-00.mono-fallback \
  -filter_complex "amix=inputs=2:duration=longest" \
  -async 1 \
  -ac 2 \
  -c:v libx264 \
  -preset ultrafast -crf 18 -r 30 \
  -c:a aac -b:a 128k \
  -avoid_negative_ts make_zero \
  /home/willc/Media/Videos/ffmpeg_caps/$(date +%Y-%m-%d_%H-%M_%S).mp4
